-- ============================================================================
-- Cosme Outlet — Supabase schema for the product catalogue + admin panel
--
-- วิธีใช้:
-- 1. เปิด Supabase Dashboard ของโปรเจกต์ (ref: hjqzrckzffqadloviaps)
-- 2. ไปที่ SQL Editor -> New query
-- 3. วางไฟล์นี้ทั้งหมด แล้วกด Run (รันครั้งเดียวพอ)
--
-- คำเตือนเรื่องความปลอดภัย:
-- เว็บนี้เป็นเว็บ static ล้วน ๆ ไม่มี server ของตัวเอง หน้า admin ป้องกันด้วย PIN
-- ที่ฝั่ง browser เท่านั้น (ไม่ใช่การยืนยันตัวตนจริงในฝั่งฐานข้อมูล) ดังนั้น policy
-- ด้านล่างจึงเปิดให้ "ทุกคนที่ถือ anon key" (ซึ่งฝังอยู่ในหน้าเว็บอยู่แล้ว และใคร ๆ
-- ก็เปิดดูได้จาก View Source) สามารถเพิ่ม/แก้/ลบสินค้าผ่าน API ได้โดยตรง แม้จะไม่ผ่าน
-- หน้า admin ก็ตาม เหมาะสำหรับเดโมหรือใช้งานภายในเท่านั้น ไม่เหมาะกับเว็บที่มีคนนอก
-- เข้าถึงจำนวนมากและข้อมูลมีความอ่อนไหว หากต้องการความปลอดภัยจริงในอนาคต ควรทำระบบ
-- login ผ่าน Supabase Auth แล้วผูก policy กับ role ที่ยืนยันตัวตนแล้วแทน
--
-- ห้ามนำ service_role key หรือรหัสผ่านฐานข้อมูล (postgresql://...) มาใส่ในโค้ดหน้าเว็บ
-- โดยเด็ดขาด เพราะจะเท่ากับเปิดสิทธิ์ระดับสูงสุดของฐานข้อมูลให้ใครก็ได้ที่เปิดดูโค้ดหน้าเว็บ
-- ============================================================================

-- ---------- 1) ตารางสินค้า ----------
create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  category    text not null check (category in ('perfume', 'skincare', 'cosmetics')),
  price       numeric(10, 2) not null default 0,
  description text not null default '',
  image_url   text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.products is 'สินค้าที่แสดงในหน้า products.html ของ Cosme Outlet';

-- เก็บเวลาแก้ไขล่าสุดอัตโนมัติ
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

-- ---------- 2) Row Level Security ----------
alter table public.products enable row level security;

drop policy if exists "Public read access" on public.products;
create policy "Public read access" on public.products
  for select using (true);

drop policy if exists "Public insert access" on public.products;
create policy "Public insert access" on public.products
  for insert with check (true);

drop policy if exists "Public update access" on public.products;
create policy "Public update access" on public.products
  for update using (true) with check (true);

drop policy if exists "Public delete access" on public.products;
create policy "Public delete access" on public.products
  for delete using (true);

-- ---------- 3) Storage bucket สำหรับรูปสินค้าที่อัปโหลดจากหน้า admin ----------
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "Public read product images" on storage.objects;
create policy "Public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

drop policy if exists "Public upload product images" on storage.objects;
create policy "Public upload product images" on storage.objects
  for insert with check (bucket_id = 'product-images');

drop policy if exists "Public update product images" on storage.objects;
create policy "Public update product images" on storage.objects
  for update using (bucket_id = 'product-images') with check (bucket_id = 'product-images');

drop policy if exists "Public delete product images" on storage.objects;
create policy "Public delete product images" on storage.objects
  for delete using (bucket_id = 'product-images');

-- ---------- 4) ข้อมูลสินค้าเริ่มต้น (24 รายการเดิมจากหน้าเว็บ) ----------
-- ใช้รูปเดิมที่ดาวน์โหลดไว้ในเว็บ (assets/images/products/...) จึงไม่ต้องอัปโหลดใหม่
insert into public.products (name, category, price, description, image_url) values
('สบู่เหลวอาบน้ำ Bath & Body กลิ่น Japanese Blossom สีแดง 295ml', 'perfume', 890, 'สบู่เหลวอาบน้ำหอมกลิ่นซากุระอ่อนหวาน ทำความสะอาดผิวนุ่มลื่น หอมติดผิวยาวนาน', 'assets/images/products/soap-japanese-blossom.webp'),
('โลชั่นน้ำหอมบำรุงผิว Victoria''s Secret กลิ่น Sultry Berry Bourbon 236ml', 'perfume', 799, 'โลชั่นบำรุงผิวเนื้อครีมเนียนนุ่ม กลิ่นเบอร์รี่หอมหวานเซ็กซี่ ผิวชุ่มชื้นทั้งวัน', 'assets/images/products/vs-lotion-sultry-berry.webp'),
('โลชั่นน้ำหอมบำรุงผิว Victoria''s Secret กลิ่น Bare Vanilla ก้อนเมฆ 236ml', 'perfume', 799, 'กลิ่นวานิลลาหอมนุ่มละมุน เนื้อบางเบาสูตรก้อนเมฆ ซึมไว ไม่เหนียวเหนอะ', 'assets/images/products/vs-lotion-bare-vanilla-cloud.webp'),
('โลชั่นน้ำหอมบำรุงผิว Victoria''s Secret กลิ่น Bare Vanilla 236ml', 'perfume', 799, 'กลิ่นวานิลลาหอมละมุนคลาสสิก บำรุงผิวนุ่มชุ่มชื้นตลอดวัน', 'assets/images/products/vs-lotion-bare-vanilla.webp'),
('โลชั่นน้ำหอมบำรุงผิว Victoria''s Secret กลิ่น Aqua Kiss สีฟ้าน้ำทะเล 236ml', 'perfume', 799, 'กลิ่นหอมสดชื่นดั่งสายลมทะเล ให้ผิวเนียนนุ่มหอมสดใสทั้งวัน', 'assets/images/products/vs-lotion-aqua-kiss.webp'),
('โลชั่นน้ำหอมบำรุงผิว Bath & Body กลิ่น Japanese Blossom สีแดง 226ml', 'perfume', 699, 'กลิ่นซากุระหอมหวานอ่อนละมุน บำรุงผิวเนียนนุ่มหอมสบายทั้งวัน', 'assets/images/products/bb-lotion-japanese-blossom.webp'),
('โลชั่นน้ำหอมบำรุงผิว Bath & Body กลิ่น Into the Night 226g', 'perfume', 699, 'กลิ่นหอมเซ็กซี่ลึกลับ เหมาะสำหรับค่ำคืนพิเศษ บำรุงผิวนุ่มชุ่มชื้น', 'assets/images/products/bb-lotion-into-the-night.webp'),
('โลชั่น Victoria''s Secret กลิ่น Bare Vanilla (กระปุกแบ่งขาย) 30ml', 'perfume', 149, 'กลิ่นวานิลลาหอมละมุน ไซส์กระปุกพกพาสะดวก คุ้มค่าคุ้มราคา', 'assets/images/products/vs-lotion-mini-bare-vanilla.webp'),

('OLAPLEX เซ็ต 3 ชิ้น (No.3, 4, 5)', 'skincare', 499, 'ชุดบำรุงเส้นผมสูตรซ่อมแซมโครงสร้างผมเสีย ลดผมขาดหลุดร่วง ผมนุ่มสวยเงางาม', 'assets/images/products/olaplex-set-3.webp'),
('La Mer The Lifting Firming Serum เซรั่ม 3ml', 'skincare', 299, 'เซรั่มบำรุงผิวหน้าสูตรยกกระชับ ลดเลือนริ้วรอย ผิวแน่นกระจ่างใสขึ้น', 'assets/images/products/lamer-lifting-serum.webp'),
('Eucerin Spotless Brightening Body Lotion 250ml', 'skincare', 589, 'โลชั่นบำรุงผิวกายสูตรลดจุดด่างดำ ผิวกระจ่างใสเรียบเนียนขึ้นอย่างเห็นผล', 'assets/images/products/eucerin-body-lotion.webp'),
('เซ็ต Sulwhasoo Signature Routine Kit 5 ชิ้น', 'skincare', 299, 'ชุดบำรุงผิวหน้าสูตรสมุนไพรเกาหลี ครบทุกขั้นตอน ผิวกระจ่างใสเปล่งปลั่ง', 'assets/images/products/sulwhasoo-signature-kit.webp'),
('สเปรย์น้ำแร่ Evian Facial Spray 400ml', 'skincare', 399, 'สเปรย์น้ำแร่บริสุทธิ์จากฝรั่งเศส ให้ความชุ่มชื้นผิวหน้าทันที สดชื่นตลอดวัน', 'assets/images/products/evian-facial-spray.webp'),
('มาสก์หน้า IPSA Luminizing Clay EX 15ml', 'skincare', 149, 'มาสก์ดินสูตรกระจ่างใส ช่วยดูดซับสิ่งสกปรกและความมัน ผิวเนียนใสขึ้น', 'assets/images/products/ipsa-clay-mask.webp'),
('มาสก์บำรุงผม Kérastase Première 75ml', 'skincare', 599, 'ทรีตเมนต์บำรุงผมเข้มข้น ซ่อมแซมเส้นผมลึกถึงแกนผม นุ่มสวยเงางาม', 'assets/images/products/kerastase-hair-mask.webp'),
('โฟมล้างหน้า Sulwhasoo The Ultimate S 40ml', 'skincare', 199, 'โฟมล้างหน้าสูตรสมุนไพรเกาหลี ทำความสะอาดล้ำลึกโดยไม่ทำให้ผิวแห้งตึง', 'assets/images/products/sulwhasoo-cleansing-foam.webp'),

('ลิป HERA เบอร์ #321 Strawberry Red', 'cosmetics', 199, 'ลิปสติกเนื้อแมทสีแดงสตรอว์เบอร์รี่ ติดทนนาน สีสวยคมชัด', 'assets/images/products/hera-lip-321.webp'),
('ไฮไลต์ Benefit Dew-La-La สี Luna 3ml', 'cosmetics', 299, 'ไฮไลเตอร์เนื้อครีม เนรมิตผิวเปล่งปลั่งดั่งแสงจันทร์ ใช้งานง่ายติดทนนาน', 'assets/images/products/benefit-highlighter-luna.webp'),
('หวี Kérastase สีทอง', 'cosmetics', 299, 'หวีแต่งผมดีไซน์หรู สีทองสวยหรู ใช้งานง่ายไม่ทำร้ายเส้นผม', 'assets/images/products/kerastase-comb-gold.webp'),
('หวี Kérastase', 'cosmetics', 299, 'หวีแต่งผมคุณภาพดี ดีไซน์เรียบหรู เหมาะสำหรับจัดแต่งทรงผมทุกวัน', 'assets/images/products/kerastase-comb.webp'),
('ลิปบาล์มกล้วย PRADA 1.3g (สี U002 Banana Yellow)', 'cosmetics', 499, 'ลิปบาล์มกลิ่นกล้วยหอมน่ารัก บำรุงริมฝีปากนุ่มชุ่มชื้น พกพาสะดวก', 'assets/images/products/prada-lip-balm-banana.webp'),
('ลิป YSL Slim #77 1.2g', 'cosmetics', 599, 'ลิปสติกทรงสลิมเนื้อแมทเนียนละเอียด สีสวยหรูหราคมชัดทุกการแต่งหน้า', 'assets/images/products/ysl-slim-77.webp'),
('ลิป YSL #12 Nu Incongru สีชมพูนม (มีกล่อง)', 'cosmetics', 499, 'ลิปสติกสีชมพูนมนู้ดสวยเป็นธรรมชาติ มาพร้อมกล่องครบ เหมาะเป็นของขวัญ', 'assets/images/products/ysl-12-nu-incongru.webp'),
('ลิป YSL #10 Brazen Nude 1.3g', 'cosmetics', 499, 'ลิปสติกสีนู้ดสวยหรู เนื้อเนียนละเอียด ให้ริมฝีปากดูอิ่มฟูเป็นธรรมชาติ', 'assets/images/products/ysl-10-brazen-nude.webp')
on conflict (name) do nothing;

-- เสร็จแล้ว! ตรวจสอบได้ที่ Table Editor -> products (ควรมี 24 แถว)
